trigger:
  branches:
    include:
    - '*'  # Trigger on any branch
  paths:
    include:
    - mssql_python/pybind/ddbc_bindings.cpp
    - mssql_python/pybind/CMakeLists.txt
    - pybuild-pipeline.yml

pr:
  branches:
    include:
    - main # Trigger on PRs to main branch
  paths:
    include:
    - mssql_python/pybind/ddbc_bindings.cpp
    - mssql_python/pybind/CMakeLists.txt
    - pybuild-pipeline.yml

jobs:
- job: BuildOnWindows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.13'
      addToPath: true
      githubToken: $(GITHUB_TOKEN)
    displayName: 'Use Python 3.13'
  - script: |
      pip install pybind11
    displayName: 'Install pybind11'
  # @gaurav to check if we can pass a release/debug flag to the cmake command
  # @gaurav to check if we can add dynamic branch for build statuses in README.md (currently it is hardcoded to main)
  - script: |
      cd mssql_python\pybind
      mkdir build
      cd build  
      cmake -DPython3_EXECUTABLE="python3" -DCMAKE_BUILD_TYPE=Debug ..
      cmake --build . --config Debug
      copy Debug\ddbc_bindings.pyd ..\..\ddbc_bindings.pyd
    displayName: 'Build and copy .pyd file'

  - powershell: |
      $branchName = "$(Build.SourceBranch)"
      $branchName = $branchName -replace 'refs/heads/', ''
      echo "Extracted Branch Name: $branchName"
      git config --global user.name "$(Build.RequestedFor)"
      git config --global user.email "$(Build.RequestedForEmail)"
      git config --global credential.helper store
      echo "https://$(System.AccessToken):@dev.azure.com" > ~/.git-credentials
      git checkout $branchName
      git add mssql_python/ddbc_bindings.pyd
      git commit -m "ddbc_bindings.pyd - $(Build.RequestedFor)"
      git push https://$(System.AccessToken)@dev.azure.com/sqlclientdrivers/mssql-python/_git/mssql-python HEAD:$branchName
    displayName: 'Commit and push .pyd file'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'mssql_python/ddbc_bindings.pyd'
      ArtifactName: 'ddbc_bindings'
      publishLocation: 'Container'
    displayName: 'Publish pyd file as artifact'